# Generated by Django 5.2.12 on 2026-03-26 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0007_portalsubmission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('Employee', 'Employee'), ('Manager', 'Manager'), ('Department Chef', 'Department Chef'), ('Admin', 'Admin')], default='Employee', max_length=20),
        ),
    ]
