# Generated by Django 5.2.12 on 2026-03-27 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0008_alter_userprofile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentcomment',
            name='is_external',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='PortalNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_email', models.EmailField(max_length=254)),
                ('text', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portal_notifications', to='documents.document')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
