# Generated by Django 5.2.13 on 2026-04-18 18:48

import django.core.validators
import documents.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0009_documentcomment_is_external_portalnotification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentattachment',
            name='file',
            field=models.FileField(upload_to=documents.models.document_attachment_upload_to, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'xls', 'xlsx', 'ppt', 'pptx', 'jpg', 'jpeg', 'png', 'gif', 'webp'])]),
        ),
    ]
